# pre-commit workflow
#
# Ensures the codebase passes the pre-commit stack.
# We run this on GHA to catch issues in commits from contributors who haven't
# set up pre-commit.

name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: pip
    - uses: pre-commit/action@v3.0.0
